export const chatCard = [
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doea",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doea",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doea",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doea",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doea",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doea",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doea",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doea",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doe",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doea",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doea",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doea",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
  {
    img: "https://via.placeholder.com/50",
    name: "Jhon Doea",
    message: "Lorem Ipsum dolor sit Amet",
    date: "14.05.2022",
  },
];
